"""FinBERT classifier — generated by the Classifier Agent (Nadi).

Runs inference on test-split rows of processed_data.csv and writes
predictions_test.csv. Loads fine-tuned weights from outputs/finbert_finetuned/
when available; otherwise falls back to ProsusAI/finbert.

Standalone:  python classifier.py [src] [dst]
"""

import csv
import os
import sys

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

# Tunable hyperparameters — adjusted each retune cycle.
MAX_LENGTH = 128
THRESHOLD = 0.5
FOCUS_LABELS = []
BOOST_FACTOR = 1.25

HF_TOKEN = os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")

FINETUNED_DIR = "outputs/finbert_finetuned"
_MODEL_PATH = FINETUNED_DIR if os.path.isdir(FINETUNED_DIR) else "ProsusAI/finbert"

tokenizer = AutoTokenizer.from_pretrained(_MODEL_PATH, token=HF_TOKEN)
model = AutoModelForSequenceClassification.from_pretrained(_MODEL_PATH, token=HF_TOKEN)
model.eval()

# Fine-tuned model labels are up/down/neutral; base model uses positive/negative/neutral.
_REMAP = {"positive": "up", "negative": "down", "neutral": "neutral"}
ID2OURS = {
    i: _REMAP.get(model.config.id2label[i].lower(), model.config.id2label[i].lower())
    for i in model.config.id2label
}


def classify(title: str) -> dict:
    inputs = tokenizer(title, return_tensors="pt", truncation=True, max_length=MAX_LENGTH)
    with torch.no_grad():
        probs = torch.softmax(model(**inputs).logits, dim=1)[0]

    by_label = {ID2OURS[i]: float(p) for i, p in enumerate(probs)}
    for fl in FOCUS_LABELS:
        if fl in by_label:
            by_label[fl] *= BOOST_FACTOR
    total = sum(by_label.values())
    if total > 0:
        by_label = {k: round(v / total, 4) for k, v in by_label.items()}

    top_label = max(by_label, key=by_label.get)
    top_prob = by_label[top_label]
    return {
        "predicted_label": top_label if top_prob >= THRESHOLD else "neutral",
        "confidence": top_prob,
        "prob_up": by_label["up"],
        "prob_down": by_label["down"],
        "prob_neutral": by_label["neutral"],
    }


def main(src: str, dst: str) -> None:
    if not os.path.exists(src):
        raise FileNotFoundError(f"Source file not found: {src}")
    with open(src, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError("Source file is empty")

    # Only predict on test rows; fall back to all rows when split column is absent.
    has_split = "split" in rows[0]
    test_rows = [r for r in rows if r.get("split", "test") == "test"]
    if has_split and not test_rows:
        raise ValueError("No test-split rows found in source file")
    if not has_split:
        test_rows = rows

    # Carry split through to the last output column.
    passthrough = [c for c in rows[0].keys() if c != "split"]
    out_cols = passthrough + ["predicted_label", "confidence", "prob_up", "prob_down", "prob_neutral"]
    if has_split:
        out_cols.append("split")

    for row in test_rows:
        row.update(classify(row["article_title"]))

    os.makedirs(os.path.dirname(dst) or ".", exist_ok=True)
    with open(dst, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=out_cols)
        writer.writeheader()
        writer.writerows(test_rows)


if __name__ == "__main__":
    main(
        sys.argv[1] if len(sys.argv) > 1 else "processed_data.csv",
        sys.argv[2] if len(sys.argv) > 2 else "predictions_test.csv",
    )
