"""Classifier Agent (Nadi) — generates the classifier code and executes it.

Reads processed_data.csv and optionally retune_request.json, generates the
classifier script classifier.py (ProsusAI/finbert), runs it to generate
predictions_test.csv, and outputs both.

See docs/data_contracts.md (Handoff 2).
"""

# Standard Python imports for file, data, and system operations
import json          # Used to parse the retune request from JSON format
import os            # Used for file path manipulations and directory creation
import subprocess    # Used to spawn and run the classifier script as a subprocess
import sys           # Used for accessing command-line arguments and system path modifications
from typing import TypedDict  # Used to define the PipelineState structure

# Insert parent directory to system path to allow importing packages from workspace root
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
try:
    # Try importing from the workspace root (when running as part of a package)
    from agents.base import Agent
    from agents.state import PipelineState
except ModuleNotFoundError:
    # Fallback to local import (when running directly from the agents/ directory)
    from base import Agent
    from state import PipelineState

# Base output directory location for outputs generated by the agent
OUTPUT_DIR = "outputs"

# Template for Python classifier script. It is generated dynamically based on tuning parameters.
CLASSIFIER_TEMPLATE = """\"\"\"Generated Classifier Script.

Runs FinBERT inference on processed_data.csv and writes predictions_test.csv.
\"\"\"

# Standard Python imports for file, data, and system operations
import csv          # Used for reading and writing CSV datasets
import os           # Used for directory checks and directory creation
import sys          # Used to read command-line arguments passed to this script
import torch        # PyTorch library for tensor calculations and model inference
# Import HuggingFace transformers tools for FinBERT model & tokenizer load
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# The pre-trained FinBERT model name from Hugging Face model hub
MODEL = "ProsusAI/finbert"
# Maximum sequence length for input tokenization
MAX_LENGTH = {max_length}
# Decision threshold for predicting non-neutral label
THRESHOLD = {threshold}
# List of focus labels to apply confidence boost to
FOCUS_LABELS = {focus_labels}
# Boost factor to multiply the probability score of focus labels
BOOST_FACTOR = {boost_factor}
# Mapping model sentiment labels (positive, negative, neutral) to system expected labels (up, down, neutral)
SENTIMENT_TO_LABEL = {{"positive": "up", "negative": "down", "neutral": "neutral"}}

# Authenticate to the HF Hub when a token is in the env (higher rate limits,
# faster downloads); fall back to unauthenticated access when it is absent.
HF_TOKEN = os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")

# Load pre-trained tokenizer from HuggingFace
tokenizer = AutoTokenizer.from_pretrained(MODEL, token=HF_TOKEN)
# Load pre-trained sequence classification model from HuggingFace
model = AutoModelForSequenceClassification.from_pretrained(MODEL, token=HF_TOKEN)
# Set the model to evaluation mode (disables dropout, batch norm updates, etc.)
model.eval()

# Build a mapping from model's internal label ID to system labels (up, down, neutral)
ID2OURS = {{i: SENTIMENT_TO_LABEL[model.config.id2label[i].lower()] for i in model.config.id2label}}

def classify(title: str) -> dict:
    \"\"\"Performs sentiment analysis classification on a single article title.
    
    Args:
        title (str): The text of the article title to classify.
        
    Returns:
        dict: Dict containing predictions, confidence score, and raw probabilities.
    \"\"\"
    # Tokenize input text to generate PyTorch input tensors with truncation and max length
    inputs = tokenizer(title, return_tensors="pt", truncation=True, max_length=MAX_LENGTH)
    # Disable gradient tracking for faster and memory-efficient inference
    with torch.no_grad():
        # Get raw logit scores from model output
        logits = model(**inputs).logits
        # Convert raw logits to probabilities using Softmax activation along class dimension
        probs = torch.softmax(logits, dim=1)[0]
    
    # Construct a dictionary mapping each system label (up, down, neutral) to its float probability
    by_label = {{ID2OURS[i]: float(p) for i, p in enumerate(probs)}}
    
    # Apply confidence boost to specific focus labels if they are specified
    for fl in FOCUS_LABELS:
        # Check if the focus label is present in predictions map
        if fl in by_label:
            # Boost the label probability by the boost factor
            by_label[fl] *= BOOST_FACTOR
            
    # Normalize probabilities to sum up to 1.0 after applying the boost
    total_prob = sum(by_label.values())
    # Ensure denominator is not zero
    if total_prob > 0:
        # Divide each score by total sum and round to 4 decimal places
        by_label = {{k: round(v / total_prob, 4) for k, v in by_label.items()}}
        
    # Get the label with the highest probability
    top_label = max(by_label, key=by_label.get)
    # Get the highest probability value
    top_prob = by_label[top_label]
    
    # Decide label: use highest label if it meets threshold, otherwise default to neutral
    predicted = top_label if top_prob >= THRESHOLD else "neutral"
    
    # Return formatted prediction record
    return {{
        "predicted_label": predicted, # The chosen predicted sentiment label
        "confidence": top_prob, # Confidence score of the classification
        "prob_up": by_label["up"], # Probability for 'up' class
        "prob_down": by_label["down"], # Probability for 'down' class
        "prob_neutral": by_label["neutral"], # Probability for 'neutral' class
    }}

def main(src: str, dst: str) -> None:
    \"\"\"Main entry point for running batch inference on a source CSV file.
    
    Args:
        src (str): Path to input processed data CSV file.
        dst (str): Path to output CSV file where predictions will be written.
    \"\"\"
    # Verify input source file exists
    if not os.path.exists(src):
        # Raise FileNotFoundError if file is missing
        raise FileNotFoundError(f"Source file not found: {{src}}")
        
    # Open the source file for reading
    with open(src, newline="", encoding="utf-8") as f:
        # Create CSV DictReader
        reader = csv.DictReader(f)
        # Parse all rows into a list of dictionaries
        rows = list(reader)
        
    # Ensure source file contains rows
    if not rows:
        # Raise ValueError if file is empty
        raise ValueError("Source file is empty")
        
    # Define output headers: original headers plus prediction and split columns
    out_cols = list(rows[0].keys()) + [
        "predicted_label", "confidence", "prob_up", "prob_down", "prob_neutral", "split"
    ]
    
    # Process all rows in the dataset
    for row in rows:
        # Call classify helper to generate prediction data for the article title
        pred_data = classify(row["article_title"])
        # Update row dictionary with predicted fields
        row.update(pred_data)
        # Set the dataset split value to 'test'
        row["split"] = "test"
        
    # Ensure destination parent directory exists
    os.makedirs(os.path.dirname(dst) or ".", exist_ok=True)
    # Open output destination file for writing
    with open(dst, "w", newline="", encoding="utf-8") as f:
        # Create CSV DictWriter with headers
        writer = csv.DictWriter(f, fieldnames=out_cols)
        # Write the header line to output CSV
        writer.writeheader()
        # Write all processed rows to output CSV
        writer.writerows(rows)

# Execute main routine if script is run directly
if __name__ == "__main__":
    # Get source path from argument or default to processed_data.csv
    src_file = sys.argv[1] if len(sys.argv) > 1 else "processed_data.csv"
    # Get destination path from argument or default to predictions_test.csv
    dst_file = sys.argv[2] if len(sys.argv) > 2 else "predictions_test.csv"
    # Run the main classification routine
    main(src_file, dst_file)
"""

def generate_code(state: PipelineState) -> dict:
    """LangGraph node to read parameters from state/retune request and write classifier.py.

    Args:
        state (PipelineState): The current state of the pipeline containing config and paths.

    Returns:
        dict: A dict of updates containing the generated classifier code path, history path, and metadata.
    """
    # Initialize default threshold value for the classifier
    threshold = 0.5
    # Initialize default max sequence length for inputs
    max_length = 128
    # Initialize default list of focus labels for classification boosting
    focus_labels = []
    # Initialize default boost factor
    boost_factor = 1.25

    # Retrieve retune request JSON from state if it exists
    retune_req = state.get("retune_request")
    # Verify the retune request is a valid dictionary
    if retune_req and isinstance(retune_req, dict):
        # Retrieve suggested hyper-parameters dictionary, default to empty dict
        suggested = retune_req.get("suggested_params", {})
        # Update threshold value if provided in the suggested params
        threshold = suggested.get("threshold", threshold)
        # Update max sequence length if provided in the suggested params
        max_length = suggested.get("max_length", max_length)
        # Update boost factor if provided in the suggested params
        boost_factor = suggested.get("boost_factor", boost_factor)
        # Update focus labels list if provided in the retune request
        focus_labels = retune_req.get("focus_labels", focus_labels)

    # Determine code output path: use configured path from state or default to outputs/classifier.py
    code_path = state.get("classifier_code_path") or os.path.join(OUTPUT_DIR, "classifier.py")
    # Ensure directories in output path are created
    os.makedirs(os.path.dirname(code_path) or ".", exist_ok=True)

    # Format the classifier template code string with specific hyperparameter values
    formatted_code = CLASSIFIER_TEMPLATE.format(
        threshold=threshold,
        max_length=max_length,
        focus_labels=repr(focus_labels),
        boost_factor=boost_factor
    )

    # Open output code file for writing with UTF-8 encoding
    with open(code_path, "w", encoding="utf-8") as f:
        # Write the formatted classifier script to the file
        f.write(formatted_code)

    # Log code generation path to standard output
    print(f"[nadi] Generated classifier code at: {code_path}")

    # Keep a per-iteration copy so past retune attempts aren't lost when
    # classifier.py (the single contract file Sabina reads) gets overwritten.
    # iteration 0 = first pass before any retune; N = the Nth retune's code.
    iteration = retune_req.get("iteration", 0) if (retune_req and isinstance(retune_req, dict)) else 0
    # Determine the history archive folder directory
    history_dir = os.path.join(os.path.dirname(code_path) or ".", "classifier_history")
    # Ensure history directory is created
    os.makedirs(history_dir, exist_ok=True)
    # Determine the file path for the archived iteration file
    history_path = os.path.join(history_dir, f"classifier_iter{iteration}.py")
    # Write the exact formatted code copy to the history archive file
    with open(history_path, "w", encoding="utf-8") as f:
        f.write(formatted_code)

    # Build model metadata dictionary containing model info and active hyperparameters
    metadata = {
        "model_name": "ProsusAI/finbert",
        "fine_tuning_params": {
            "threshold": threshold,
            "max_length": max_length,
            "focus_labels": focus_labels,
            "boost_factor": boost_factor
        }
    }

    # Return pipeline state updates containing code path, history path and metadata
    return {
        "classifier_code_path": code_path,
        "classifier_history_path": history_path,
        "classifier_metadata": metadata
    }

def run_classifier(state: PipelineState) -> dict:
    """LangGraph node to run the generated classifier.py on processed_data.csv.

    Args:
        state (PipelineState): The current state of the pipeline containing code and data paths.

    Returns:
        dict: A dict of updates containing the predictions file path.
    """
    # Retrieve the path to the generated classifier Python script
    code_path = state["classifier_code_path"]
    # Retrieve data path from state or default to mock_data/processed_data.csv
    data_path = state.get("processed_data_path") or "mock_data/processed_data.csv"
    # Retrieve output predictions path from state or default to outputs/predictions_test.csv
    pred_path = state.get("predictions_path") or os.path.join(OUTPUT_DIR, "predictions_test.csv")

    # Ensure parent directories for predictions output file exist
    os.makedirs(os.path.dirname(pred_path) or ".", exist_ok=True)

    # Log the execution process to standard output
    print(f"[nadi] Running classifier: {code_path} on {data_path} -> {pred_path}")
    
    # Run the generated Python classifier script as a subprocess using the current interpreter
    subprocess.run([sys.executable, code_path, data_path, pred_path], check=True)

    # Log successful output location to standard output
    print(f"[nadi] Predictions saved to: {pred_path}")

    # Return pipeline state updates containing prediction path
    return {
        "predictions_path": pred_path
    }

def build_graph(checkpointer):
    """Compiles and builds the LangGraph state graph for the Classifier pipeline.

    Args:
        checkpointer: The LangGraph checkpointer object used for state saving/persistence.

    Returns:
        CompiledStateGraph: The compiled state graph workflow runnable.
    """
    # Import LangGraph classes locally
    from langgraph.graph import StateGraph, START, END

    # Initialize state graph builder with PipelineState schema definition
    builder = StateGraph(PipelineState)
    # Add graph node for classifier code generation
    builder.add_node("generate_code", generate_code)
    # Add graph node for running classifier script execution
    builder.add_node("run_classifier", run_classifier)
    # Add edge from START node directly to generate_code node
    builder.add_edge(START, "generate_code")
    # Add edge from generate_code node to run_classifier node
    builder.add_edge("generate_code", "run_classifier")
    # Add edge from run_classifier node to END node
    builder.add_edge("run_classifier", END)
    # Compile builder into a runnable graph workflow using provided checkpointer
    return builder.compile(checkpointer=checkpointer)

class ClassifierAgent(Agent):
    """Classifier Agent (Nadi) behind the shared `.run()` interface.

    Responsible for code generation and inference pipeline orchestration.
    """

    def __init__(self, *, checkpointer=None, thread_id="classifier"):
        """Initializes the ClassifierAgent instance.

        Args:
            checkpointer: Optional LangGraph checkpointer instance.
            thread_id (str): Thread ID configuration for state graph runs.
        """
        # Call the parent Agent class initialization
        super().__init__(checkpointer=checkpointer, thread_id=thread_id)

    def build_graph(self, checkpointer):
        """Builds the LangGraph state graph for Nadi.

        Args:
            checkpointer: The checkpointer object to persist graph state.

        Returns:
            CompiledStateGraph: The compiled state graph.
        """
        # Return compiled state graph builder utility function output
        return build_graph(checkpointer)

    def run(self, processed_data: str, classifier_code: str, predictions: str, retune_request: str | None = None) -> dict:
        """Runs the classifier generation and prediction step.
        
        Args:
            processed_data (str): Path to input processed_data.csv
            classifier_code (str): Output path for classifier.py
            predictions (str): Output path for predictions_test.csv
            retune_request (str | None): Optional path to input retune_request.json
            
        Returns:
            dict: The final invoke output dictionary state.
        """
        # Initialize pipeline state dictionary with resolved absolute path names
        state = {
            "processed_data_path": os.path.abspath(processed_data),
            "classifier_code_path": os.path.abspath(classifier_code),
            "predictions_path": os.path.abspath(predictions),
        }
        # If a retune request file path is supplied
        if retune_request is not None:
            # Check if the retune request file path actually exists
            if not os.path.exists(retune_request):
                # Log a warning to stderr if file path exists in args but file is missing
                print(
                    f"[nadi] WARNING: retune_request file path was provided but the file does not exist: {retune_request}",
                    file=sys.stderr
                )
                # Assign default text value to state to mark missing request
                state["retune_request"] = "no retune applied"
            else:
                # Attempt to open and parse the retune request file
                try:
                    # Open the file in read-mode with UTF-8 encoding
                    with open(retune_request, "r", encoding="utf-8") as f:
                        # Parse JSON object and save to state
                        state["retune_request"] = json.load(f)
                # Handle any parsing/reading errors
                except Exception as e:
                    # Print error details to stderr stream
                    print(
                        f"[nadi] ERROR: Failed to parse retune_request file {retune_request}: {e}",
                        file=sys.stderr
                    )
                    # Re-raise the exception to abort operation
                    raise e
            
        # Run state graph invocation and return execution results dict
        return self._invoke(state)

if __name__ == "__main__":
    # Import command-line parsing library
    import argparse

    # Instantiate argument parser with description message
    parser = argparse.ArgumentParser(description="Run the Classifier Agent (Nadi).")
    # Add option for processed input data CSV file path
    parser.add_argument("--processed-data", default="mock_data/processed_data.csv", help="Input CSV path")
    # Add option for output code Python script file path
    parser.add_argument("--classifier-code", default="outputs/classifier.py", help="Output Python script path")
    # Add option for output prediction CSV file path
    parser.add_argument("--predictions", default="outputs/predictions_test.csv", help="Output predictions path")
    # Add option for retune request input JSON file path
    parser.add_argument("--retune-request", default=None, help="Input retune request JSON path")
    
    # Parse command line inputs into structured namespace object
    args = parser.parse_args()

    # Create instance of ClassifierAgent class
    agent = ClassifierAgent()
    # Execute agent pipeline flow with parsed command-line arguments
    res = agent.run(
        processed_data=args.processed_data,
        classifier_code=args.classifier_code,
        predictions=args.predictions,
        retune_request=args.retune_request
    )
    # Log successful execution completion details to output stream
    print("\nClassifier completed. Predictions at:", res["predictions_path"])
